name: Docker Push

on:
  workflow_dispatch:


jobs:
  build-and-push:
    runs-on: ubuntu-20.04

    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Get Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Java Version
        run: java -version

      - name: Build Jar file
        run: mvn clean install

      - name: Docker login
      - uses: docker/login-action@v1
        with:
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}

      - name: Build and push
        uses: docker/build-push-actin@v2
        with:
          context: .
          push: true
          tags: ${{secrets.USERNAME}}/my-app:latest

      - name: Upload Jar file
        uses: actions/upload-artifact@v2
        with:
          name: my-app.jar
          path: target/Docker-test-0.0.1-SNAPSHOT.jar
#          path: target/*.jar